apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-app
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Release.Name }}-app
  type: ClusterIP
